server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/tmp/test/config-data
          default-label: master
          force-pull: true

logging:
  level:
    root: INFO
